### ISSUE TITLE
setStartPoint opens alot of connections to the db

### ISSUE THREAD

**Issue by soezen** [assertj/assertj-db#117]
When I call setStartPointNow() a lot of connections are opened.
One for getting all the tables and then the code loops over all tables and opens another connection for each table to get the table name.
Is it possible to refactor this to reuse the already open connection?

```
  public Changes setStartPointNow() {
    if (request == null && tablesList == null) {
      try (Connection connection = getConnection()) {
        tablesList = new LinkedList<>();
        DatabaseMetaData metaData = connection.getMetaData();
        ResultSet resultSet = metaData.getTables(getCatalog(connection), getSchema(connection), null,
            new String[] { "TABLE" });
        while (resultSet.next()) {
          String tableName = resultSet.getString("TABLE_NAME");
          Table t = new Table().setLetterCases(getTableLetterCase(), getColumnLetterCase(), getPrimaryKeyLetterCase())
                               .setName(getTableLetterCase().convert(tableName));
          copyElement(this, t);
          tablesList.add(t);
        }
      } catch (SQLException e) {
        throw new AssertJDBException(e);
      }
    }
   ...
```
The copyElement() method within the while loop is the place where another connection is opened to get the table name from database.
I tried to overwrite this, but many of the methods in changes are private so it seems impossible to create a workaround.

**Comment by VanRoy** [comment]
Hi @soezen , indeed it's not really easy to fix it due to the conception of `Table` implementation :(

**Comment by VanRoy** [comment]
@soezen After long time, I finally a real fix for this issue.
In the new release 3.0.0 you have more control on how connection are retreive and also the capacity to keep in memory the schema.

**Comment by soezen** [comment]
@VanRoy wow, great thanks. It comes at a good time, i will try it out soon.
