### ISSUE TITLE
Make AssertJ-DB transaction aware

### ISSUE THREAD

**Issue by r0main** [assertj/assertj-db#51]
Hi,

Context : 
 - AssertJ-DB 1.1.1 
 - Spring-Test
 - H2 Database.

 It seems that AssertJ-DB in this version is not aware of opened transactions. I looked at you test cases. Your are using `@Transactional` : 

```java
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = { TestsConfiguration.class })
@Transactional
public abstract class AbstractTest {
```

But you didn't add the `TransactionalTestExecutionListener` and you didn't create a `PlatformTransactionManager`. So I think you are not really using transactions.

The only solution that we found today is to create two classes `CachedConnectionDatasource` and `UnclosableConnection`. The trick is to give always the same connection to the caller, and give a fake instance of `Connection` that will ignore any `close()` calls. But it's more a trick than a real clean solution.

Do you think it is possible to make AssertJ-DB aware of exiting transactions ? Maybe creating a listener like in DbUnit and other frameworks ?

**Comment by VanRoy** [comment]
Hi @r0main @anthonyraymond , I think you can solve this issue with use of `TransactionAwareDataSourceProxy`from spring-tx

`
Table table = new Table(TransactionAwareDataSourceProxy(dataSource), "products");
`

**Comment by anthonyraymond** [comment]
@VanRoy I wasn't aware of that class, thanks to you. It works indeed

**Comment by VanRoy** [comment]
@anthonyraymond Cool. Thanks for your feedback.
