### ISSUE TITLE
When update table on schema, the Changes object has deletion and creation, not one modification

### ISSUE THREAD

**Issue by sciencesakura** [assertj/assertj-db#91]
* version: 2.0.0

```sql
-- without schema
create table table_a (
  id    bigint      not null,
  name  varchar(50) not null,
  primary key (id)
);

-- with schema
create table abc.table_b (
  id    bigint      not null,
  name  varchar(50) not null,
  primary key (id)
);
```

On the one hand, when update table without schema, the `Changes` has **one modification change**:

```java
var changes = new Changes(dataSource);
changes.setStartPointNow();
// exec `update table_a set ... where id = 1`
changes.setEndPointNow();
assertThat(changes).hasNumberOfChanges(1) // PASSED
            .change()
            .isModification();
```

But on the other hand, when update table with schema, the `Changes` has **two changes - creation and deletion**:

```java
var changes = new Changes(dataSource);
changes.setStartPointNow();
// exec `update abc.table_b set ... where id = 1`
changes.setEndPointNow();
assertThat(changes).hasNumberOfChanges(1) // FAILED
            .change()
            .isModification();
assertThat(changes).hasNumberOfChanges(2) // PASSED
            .change()
            .isCreation()
            .change()
            .isDeletion();
```

I think an update operation should be treated as one modification always, not a pair of deletion and creation.

**Comment by sciencesakura** [comment]
I put simple code to reproduce this behavior:

https://github.com/sciencesakura/assertj-db-issues-reproduction/tree/issue_91

**Comment by sciencesakura** [comment]
Hi, I've solved it.

`Changes` obtains table and primary key definitions from the metadata using the connection's current schema. Thus when verifying the table that belongs to the different schema from connection's current one, the verifying is not work correctly.

So I've created separate `Changes` for each schema and asserted them individually:

```java
var changesPublic = new Changes(new Source("jdbc:h2:mem:test", ...));
var changesAbc = new Changes(new Source("jdbc:h2:mem:test;SCHEMA=ABC", ...));

assertThat(changesPublic)...; // for PUBLIC schema only
assertThat(changesAbc)...;    // for ABC schema only
```

It work.

I'll close this. thx

**Comment by VanRoy** [comment]
Hi @sciencesakura , thanks a lot for the feedback, your investigation and for sharing the solution.
